language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag ndiklasthecoder:v16 ndiklasthecoder/reverseproxy:v16
  - docker tag udagram-frontend:v17 ndiklasthecoder/udagram-frontend:v17
  - docker tag udagram-api-user:v16 ndiklasthecoder/udagram-api-user:v16
  - docker tag udagram-api-feed:v16 ndiklasthecoder/udagram-api-feed:v16

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ndiklasthecoder/reverseproxy:v42
  - docker push ndiklasthecoder/udagram-frontend:v42
  - docker push ndiklasthecoder/udagram-api-user:v42
  - docker push ndiklasthecoder/udagram-api-feed:v42

